version: '3.9'
services:
  app:
    platform: linux/amd64
    container_name: helpr-app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - .:/app
  api:
    platform: linux/amd64
    container_name: helpr-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    volumes:
      - .:/api
