version: '3.9'
services:
  app:
    container_name: helpr-app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8081:3000"
    env_file:
      - .env
  api:
    container_name: helpr-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    env_file:
      - .env
